name: hw-string-parse
version: '0.0.0.4'
synopsis: String parser
description: Please see README.md
category: Data, Bit
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-string-parse
homepage: http://github.com/haskell-works/hw-string-parse#readme
extra-source-files:
- README.md
ghc-options: -Wall
dependencies:
- base >=4 && <5
library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.String.Parse
tests:
  hw-string-parse-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - hspec
    - hw-string-parse
    - QuickCheck
    - vector
stability: Experimental
